fix submit and checkbox of terms and conditions
codescalers/cloud4students pull request #243
Opened 2023-05-10 13:43 UTC by samaradel

- https://github.com/codescalers/cloud4students/issues/230
- https://github.com/codescalers/cloud4students/issues/231

2023-05-14 09:25 UTC, rawdaGastan requested changes
I don't think https://github.com/codescalers/cloud4students/issues/230 is resolved?

2023-05-14 09:25 UTC, rawdaGastan commented on client/src/views/Signup.vue
>          if (value < 1) return "Team Size should at least 1";
`Team Size should be at least 1` add `be`

2023-05-14 13:12 UTC, samaradel commented
> I don't think #230 is resolved?

[Screencast from 14-05-23 16:09:35.webm](https://github.com/codescalers/cloud4students/assets/11662805/6e2046db-5c89-4cb0-bebb-ac1290c940ab)

2023-05-15 14:58 UTC, samaradel commented
> I don't think #230 is resolved?

as per our discussion, it fixed now

2023-05-16 14:14 UTC, rawdaGastan approved these changes

2023-05-16 14:14 UTC, rawdaGastan commented on client/src/views/Signup.vue
> +        if (!value) return "Field is required";
why did you remove it?
`if (!value.match(nameRegex)) return "Must be at most four names";`

2023-05-17 07:44 UTC, samaradel commented on client/src/views/Signup.vue
> +        if (!value) return "Field is required";
removed by mistake, fixed now

2023-05-17 08:28 UTC, rawdaGastan approved these changes

2023-05-17 08:37 UTC, merged